name: Node.js CI

on: [push]

env:
  CI: true
  ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
  CHAIN: ${{ secrets.CHAIN }}
  INFURA_KEY: ${{ secrets.INFURA_KEY }}
  BONUS_THRESHOLD: 0.1

defaults:
  run:
    working-directory: loadSearcher

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm ci --no-audit
      - run: npm run lint --if-present
      - run: npm test
      - run: npm run build --if-present
