name: Node.js CI

on: [push]

env:
  CI: true
  ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
  CHAIN: ${{ secrets.CHAIN }}
  BONUS_THRESHOLD: 0.1
  AAVE_V2_LENDING_POOL_ADDRESS_PROVIDER: "0xb53c1a33016b2dc2ff3653530bff1848a515c8c5"
  TEST_USER_TO_LIQUIDATE: "0x8a8967428b96b9c64d5f578b25ab20c378abb896"
  TEST_BLOCK_NUMBER: 14367536

defaults:
  run:
    working-directory: loanSearcher

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: loanSearcher/package-lock.json
      - run: npm ci --no-audit
      - run: npm run lint --if-present
      - run: npm test
      - run: npm run build --if-present
  slack-status:
    if: always()
    name: "Slack Updates"
    needs:
      - build
    runs-on: ubuntu-latest

    steps:
      - name: Slack Workflow Notification
        uses: Gamesight/slack-workflow-status@master
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK }}
          include_commit_message: true
          include_jobs: true
          icon_url: https://ca.slack-edge.com/T030RM510F3-U03P463RU95-1f115892cbd1-72
