name: Node.js CI

on: [push]

env:
  CI: true
  ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
  CHAIN: ${{ secrets.CHAIN }}
  INFURA_KEY: ${{ secrets.INFURA_KEY }}
  BONUS_THRESHOLD: 0.1
  AAVE_V2_LENDING_POOL_ADDRESS_PROVIDER: "0xb53c1a33016b2dc2ff3653530bff1848a515c8c5"

defaults:
  run:
    working-directory: loanSearcher

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: subdir/package-lock.json
      - run: npm ci --no-audit
      - run: npm run lint --if-present
      - run: npm test
      - run: npm run build --if-present
